// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqAsLGBmkcFuTCoOurbiF9WhjKiz9VrY',
    appId: '1:313118057414:web:65cc51fb0a2dca68ba08c7',
    messagingSenderId: '313118057414',
    projectId: 'fir-app-420fc',
    authDomain: 'fir-app-420fc.firebaseapp.com',
    storageBucket: 'fir-app-420fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnIaCvtgEtPJdpTUtaVZ5k0svE4lzMmeA',
    appId: '1:313118057414:android:c27f5d1ef56d870fba08c7',
    messagingSenderId: '313118057414',
    projectId: 'fir-app-420fc',
    storageBucket: 'fir-app-420fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAReq4BBfyUpCb0AlXOr70LenwAj4UtNwM',
    appId: '1:313118057414:ios:46eb47631462c633ba08c7',
    messagingSenderId: '313118057414',
    projectId: 'fir-app-420fc',
    storageBucket: 'fir-app-420fc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAReq4BBfyUpCb0AlXOr70LenwAj4UtNwM',
    appId: '1:313118057414:ios:46eb47631462c633ba08c7',
    messagingSenderId: '313118057414',
    projectId: 'fir-app-420fc',
    storageBucket: 'fir-app-420fc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALqAsLGBmkcFuTCoOurbiF9WhjKiz9VrY',
    appId: '1:313118057414:web:660f39215e97e3deba08c7',
    messagingSenderId: '313118057414',
    projectId: 'fir-app-420fc',
    authDomain: 'fir-app-420fc.firebaseapp.com',
    storageBucket: 'fir-app-420fc.firebasestorage.app',
  );

}